### ISSUE TITLE
 cannot unmarshal !!str `run -c ...` into []string

### ISSUE THREAD

**Issue by holywen** [digibib/docker-compose-dot#1]
docker-compose-dot test.yml
2017/02/02 08:34:20 yaml: unmarshal errors:
  line 6: cannot unmarshal !!str `run -c ...` into []string

cat test.yml
```
version: '2'

services:
  interlock:
    image: ehazlett/interlock:master
    command: run -c /etc/interlock/config.toml
    volumes:
        - ./interlock/config.toml:/etc/interlock/config.toml
        - ./interlock/haproxy.cfg.template:/usr/local/etc/interlock/haproxy.cfg.template
        - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by brinxmat** [comment]
What version of docker-compose are you using? And your OS?

**Comment by holywen** [comment]
On MacOS,  
docker-compose -v
`docker-compose version 1.10.0, build 4bd6f1a`

**Comment by bensinober** [comment]
Hi,

you will need to make 'command' an array, not inline, thus:
```
---
version: '2'

services:
  interlock:
    image: ehazlett/interlock:master
    command:
      - "run -c /etc/interlock/config.toml"
    volumes:
      - ./interlock/config.toml:/etc/interlock/config.toml
      -
./interlock/haproxy.cfg.template:/usr/local/etc/interlock/haproxy.cfg.template
      - /var/run/docker.sock:/var/run/docker.sock
```

just a shortcoming in the app, of the parsing of yaml to go structs

2017-02-03 0:15 GMT+01:00 holywen <notifications@github.com>:
